name: Build and Pack
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Pack CRX
        run: pnpm run pack:crx
      - name: Pack XPI
        run: pnpm run pack:xpi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extension-artifacts
          path: |
            extension
            extension.crx
            extension.xpi
